### ISSUE TITLE
[Combobox] Popover renders before element is focused if initialized with a value

### ISSUE THREAD

**Issue by cbarringer** [reach/reach-ui#464]
### Current Behavior

If a combobox is initialized with a value and the `openOnFocus` prop set to true, the combobox will render as open before the user navigates focus to the input.

<img width="367" alt="Screen Shot 2020-02-11 at 3 47 36 PM" src="https://user-images.githubusercontent.com/28166188/74290243-1bc05500-4ce6-11ea-8725-33b30942d744.png">

### Expected behavior

The combobox popover should only render once the user has focused on the combobox input, even if an initial value is specified.

### Reproducible example

https://codesandbox.io/s/gallant-wilson-x5ezd

### Suggested solution(s)

This line is the root of this bug: https://github.com/reach/reach-ui/blob/master/packages/combobox/src/index.tsx#L452

On initial render of a combobx with an initial value, the change handler is being triggered inappropriately.

In order to fix this, two things are needed:

1. Determine the difference between an initial and new value
2. Dispatch different events for each

One proposed solution is to add an additional action to the combobox reducer to `INITIALIZE` a value. Additional state would need to be added to distinguish the case of setting an initial value from the case of setting a new value after the initial value is set. The `INITIALIZE` action could change the value without transitioning the state from `IDLE` to `SELECTING`, and could set a flag in the state indicating that an `INITIALIZE` action has already been dispatched.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    |  @reach/combobox       |  0.8.2       |
| React            |    react, react-dom     |  16.9.0       |
| Browser          |    chrome     |    80.0.3987.87      |
| Assistive tech   |         |         |
| Node             |   node      |   12.13.1      |
| npm/yarn         |     yarn    | 1.19.1        |
| Operating System |    MacOS     |     10.14.6    |

**Comment by chancestrickland** [comment]
Should be fixed in 0.8.3

**Comment by geekus** [comment]
This is an issue in 0.13.0 too, so probably wasn't fixed or has been re-introduced.
