### ISSUE TITLE
Rendering bug in either descendants or react

### ISSUE THREAD

**Issue by lifeiscontent** [reach/reach-ui#821]
### Current Behavior

I might of setup my test case wrong, but I think its right.

I've written tests for React Testing Library as well as a helper to check if the bug is present.

5% of the time the descendants code will register the wrong indexes.

### Expected behavior

no indexes to be wrong.

### Reproducible example

[CodeSandbox Example](https://codesandbox.io/s/quirky-bohr-gcjqw)
[GitHub Source](https://github.com/lifeiscontent/descendants-bug)

### Suggested solution(s)

again, not sure what the issue is here, and quite possibly could be a bug in react.

### Additional context

You can run the example app locally, and use this code to mimic the test I have written.

```js
function testcase() {
    document.querySelector('button').click();
    Array.from(document.querySelectorAll('span')).forEach(el => {
      console.assert(el.textContent.endsWith(el.parentElement.getAttribute('data-index')))
    })
}

// once testcase is defined in the console, call this {n} times till you see the assert error.

testcase();
```

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    | descendants        | 0.15.3        |
| React            |    react     |  17.0.2       |
| Browser          |        chrome  | 92.0.4515.107        |
| Assistive tech   |     N/A    |         |
| Node             |    node     |       14.17.3  |
| npm/yarn         |    npm     |      7.20.1   |
| Operating System |    Zorin OS Linux     |  16       |

**Comment by indiesquidge** [comment]
@lifeiscontent thanks for including a sandbox! Please be aware that the [descendants][1] package is not (at least yet) meant to be used directly outside of Reach UI, so be careful shipping it in any production project.

Your example code is a bit tricky to use as a determiner for the issue you're describing, particularly because you're saying that the issue appears effectively at random and your code contains randomization code. Are you able to reproduce the problem any more deterministically? It would greatly help to reduce the number of variables (especially random ones) surrounding the issue.

**Comment by lifeiscontent** [comment]
@indiesquidge thanks for the warning, I'm building a UI kit and I've run into a similar problem that descendants tries to solve.

I wrote the test because I wanted to understand the problem, in regards to the randomization the tests; although random, they are stable it is used to cover a wide range of possible tree structures quickly and to make sure that the index registration from useDecedent is correct.

happy to hop on a call and discuss or share any more details you might need.

I'll see if I can simplify the tests to something more deterministic, but the issue might be a race condition in which case it would be a bug in React, or that the descendants implementation is not something that can be correctly modeled with useLayoutEffect hooks.

**Comment by chaance** [comment]
Thanks for this @lifeiscontent, will take a look this weekend 👍

**Comment by chaance** [comment]
The good news: I do believe you found a bug, and I *think* it should be fixed in the next release. Thanks for that! It'll change some of our APIs a bit and require a little more boilerplate in the consumer packages, but this is technically an internal package so I'm not super concerned about that.

That said, even with the fix, I'm not sure it'll work for your use case here. I don't know that we need that sort of descendant nesting you're going for. If you can get it to work consistently and keep things performant I'll be happy to take a PR, but just as a disclaimer it's possible that we keep changing things indiscriminately without regards to semver, so I might still fork it or try your own solution if you're currently using it directly.

**Comment by chaance** [comment]
Closing because I think I found and fixed the bug, but I added a note to the release to explain the potential unexpected issues you might encounter along the way. Descendants are only registered/unregistered when new items enter/leave the list but *not* when existing items move around.

**Comment by lifeiscontent** [comment]
@chaance I just took a look at the updates, still doesn't work as I'd expect, the stories you added to reach/descendants I think might be too simple, the sorting story only goes 1 level deep the example I put together explicitly had 2 levels of nesting because it the package is called "descendants" I'd expect it to be able to register the elements in the correct order regardless of where it was in the tree.

this test: https://github.com/lifeiscontent/descendants-bug/blob/master/src/App.test.tsx

passes the first render, but all 100 renders in the second test now fail.

can you take a look at the example I've put together to see if I'm setting the demo up correctly?

https://github.com/lifeiscontent/descendants-bug/blob/master/src/Reach.tsx

**Comment by lifeiscontent** [comment]
@chaance sorry, I forgot to push, updated now.
