### ISSUE TITLE
dialog: focus-trap blocks interactive elements rendered using portal

### ISSUE THREAD

**Issue by kirillku** [reach/reach-ui#83]
Hi, thanks for the `Dialog`. It works great but I face one issue. You are using `focus-trap` internally to block events outside the `Dialog`, which is nice and I understand the logic behind this. I am rendering some interactive elements inside the `Dialog` and some of them are also using portals for rendering (for example popups), which results them being not a child node of the `Dialog` and this why not active. They are visible, but not clickable. Can you suggest some solution or workaround? I didn't come up with anything. Maybe it's possible to only block click events on the elements, that are above the `Dialog` in the DOM tree.

**Comment by everdimension** [comment]
Interesting case.

I think the right solution is to make your portal elements render inside the dialog component. It actually makes sense.

The reason for rendering tooltips and popups as a direct child of body is usually either dealing with css specificity or z-index wars. And since you have a modal dialog open, you're already rendering your elements outside the main app root. There should be no need to render popups in a parallel branch.

**Comment by kirillku** [comment]
Yep, this is what I would do with my own components to solve the issue, but what about third party ones. For example [react-semantic-ui Popup](http://react.semantic-ui.com/modules/popup/).

Also, the reasoning behind putting something in a portal can be not only z-index, but also overflow positioning.

**Comment by everdimension** [comment]
> Yep, this is what I would do with my own components to solve the issue, but what about third party ones. For example react-semantic-ui Popup.

I had similar problems with 3rd party libraries and I've came to the conclusion that those libs that do not let you configure the root container they attach to are not very good libraries :) And it is a good idea to open an issue in their repository.

I understand that this is not the answer you were hoping for, but it seems to me to be the "right" way to deal with this.

---

Also I wonder whether the `@reach/dialog` allows you to specify a root other than the body 🤔  
Seems to me that it doesn't https://github.com/reach/reach-ui/blob/master/packages/portal/src/index.js#L10 🙁

**Comment by kirillku** [comment]
What about making `disableFocusTrap` prop for such cases. I think there is a lot 3rd party libs, that only attach portals as direct children of body. I will do a mr for that.

**Comment by theKashey** [comment]
[react-focus-lock](https://github.com/theKashey/react-focus-lock) could be a solution here - it uses React event propagation, not DOM, thus focus events, as long as they would _bubble_ from portals, are visible to lock, and are considered as their own.
But first we have to remove focus-trap from reach/dialog.

**Comment by ryanflorence** [comment]
ah! this is likely the problem with #64, would love somebody to explore using react-focus-lock and send a PR using it?

**Comment by theKashey** [comment]
Probably that should be on me.

**Comment by Miklet** [comment]
We are facing currently same issue with `focus-trap`. Wouldn't be better to add additional prop on `Dialog` wchich will let us configure `focus-trap` when initializing it with `createFocusTrap`?

**Comment by chancestrickland** [comment]
I *believe* this issue has been resolved but simply not closed, but if folks are still having trouble here please flag me and I'll happily reopen and investigate further.

**Comment by theKashey** [comment]
So it works if you can "click" on portaled elements, and that would properly bubble from react tree, and managed, but in terms of "focus trapping" - there is no way you can "tab" into portaled content.
It's not a big deal to _discover_ them, but probably Flare would be a more safe way to handle it. So - let's wait a bit.

**Comment by paulrberg** [comment]
> I believe this issue has been resolved but simply not closed, but if folks are still having trouble here please flag me and I'll happily reopen and investigate further.

No, this isn't solved yet. I've encountered the same focus trap issue in v0.15.2. If I assign `display: none` to the Reach Dialog tag in Chrome, I can interact with the input. Otherwise, I can't.

I'm loading a third-party widget that appends a `div` child directly to `body`; the third-party widget doesn't let me choose the root container.
